services:
  - type: web
    name: wifi-sensing-demo
    env: python
    runtime: python-3.9
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p models csi_samples results
    startCommand: |
      PORT=${PORT:-10000}
      echo "Starting Streamlit on port $PORT"
      
      export STREAMLIT_SERVER_PORT=$PORT
      export STREAMLIT_SERVER_ADDRESS=0.0.0.0
      export STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      export STREAMLIT_SERVER_HEADLESS=true
      export STREAMLIT_SERVER_ENABLE_CORS=false
      export STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
      export STREAMLIT_SERVER_ENABLE_WEBSOCKET_COMPRESSION=true
      
      exec streamlit run app.py
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: STREAMLIT_SERVER_MAX_UPLOAD_SIZE
        value: 200
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: true
      - key: STREAMLIT_SERVER_ENABLE_WEBSOCKET_COMPRESSION
        value: true
      - key: HEALTH_CHECK
        value: false 