services:
  - type: web
    name: wifi-sensing-demo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: $PORT 